# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: teb.afterstory::lang.menu.name

# Model Form Field configuration
form: @/plugins/teb/afterstory/models/comment/fields.yaml

# Model Class name
modelClass: Teb\AfterStory\Models\Comment

# Default redirect location
defaultRedirect: teb/afterstory/comments

# Update page
update:
    title: teb.afterstory::lang.form.update
    redirect: teb/afterstory/comments
    redirectClose: teb/afterstory/comments
    flash-save: teb.afterstory::lang.form.flashupdate
    flash-delete: teb.afterstory::lang.form.flashdelete

# Preview page
preview:
    title: teb.afterstory::lang.form.preview

