# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: teb.afterstory::lang.menu.name

# Model Form Field configuration
form: @/plugins/teb/afterstory/models/post/fields.yaml

# Model Class name
modelClass: Teb\AfterStory\Models\Post

# Default redirect location
defaultRedirect: teb/afterstory/posts

# Create page
create:
    title: teb.afterstory::lang.form.create
    redirect: teb/afterstory/posts/update/:id
    redirectClose: teb/afterstory/posts
    flash-save: teb.afterstory::lang.form.flashcreate

# Update page
update:
    title: teb.afterstory::lang.form.update
    redirect: teb/afterstory/posts
    redirectClose: teb/afterstory/posts
    flash-save: teb.afterstory::lang.form.flashupdate
    flash-delete: teb.afterstory::lang.form.flashdelete

# Preview page
preview:
    title: teb.afterstory::lang.form.preview

